import ImagePage from '../../support/global/imagePage'
import imagePackInImagePage from '../../support/global/imagePackInImagePage.js'
describe('Go to image page in .de',function()
{

    it('Image page assertions RM',function()
    {
        const ip = new ImagePage()
        ip.imagePage_visit_RM('de')
        ip.imagePage_license_personalUse_RM('de')
        ip.imagePage_license_personalUse_price_check_RM('de')
        ip.imagePage_license_presentation_RM('de')
        ip.imagePage_license_presentation_price_check_RM('de')
        ip.imagePage_license_website_RM('de')
        ip.imagePage_license_website_price_check_RM('de')
        ip.imagePage_license_Magazines_and_books_RM('de')
        ip.imagePage_license_Magazines_and_books_price_check_RM('de')
        ip.imagePage_license_Marketing_package_Small_business_RM('de')
        ip.imagePage_license_Marketing_package_Small_business_price_check_RM('de')
        ip.imagePage_license_Marketing_package_Large_business_RM('de')
        ip.imagePage_license_Marketing_package_Large_business_price_check_RM('de')
    })

    it('Image page assertions RF',function()
    {
        const ip = new ImagePage()
        ip.imagePage_visit_RF('de')
        ip.imagePage_license_personalUse_RF('de')
        ip.imagePage_license_personalUse_price_check_RF('de')
        ip.imagePage_license_presentation_RF('de')
        ip.imagePage_license_presentation_price_check_RF('de')
        ip.imagePage_license_website_RF('de')
        ip.imagePage_license_website_price_check_RF('de')
        ip.imagePage_license_Magazines_and_books_RF('de')
        ip.imagePage_license_Magazines_and_books_price_check_RF('de')
        ip.imagePage_license_Marketing_package_Small_business_RF('de')
        ip.imagePage_license_Marketing_package_Small_business_price_check_RF('de')
        ip.imagePage_license_Marketing_package_Large_business_RF('de')
        ip.imagePage_license_Marketing_package_Large_business_price_check_RF('de')
    })

    it('Image page assertions vector',function()
    {
        const ip = new ImagePage('de')
        ip.imagePage_visit_vector('de')
        ip.imagePage_license_vector('de')
        ip.imagePage_license_vector_price_check('de')
    })

    it('Image page assertions 360',function()
    {
        const ip = new ImagePage()
        ip.imagePage_visit_360('de')
        ip.imagePage_license_Website_or_social_media_site_360('de')
        ip.imagePage_license_Website_or_social_media_site_price_check_360('de')
        ip.imagePage_license_VR_or_game_apps_360('de')
        ip.imagePage_license_VR_or_game_apps_price_check_360('de')
        ip.imagePage_license_Digital_publishing_360('de')
        ip.imagePage_license_Digital_publishing_price_check_360('de')
        ip.imagePage_license_TV_program_360('de')
        ip.imagePage_license_TV_program_price_check_360('de')
        ip.imagePage_license_Marketing_package_Small_business_360('de')
        ip.imagePage_license_Marketing_package_Small_business_price_check_360('de')
        ip.imagePage_license_Marketing_package_Large_business_360('de')
        ip.imagePage_license_Marketing_package_Large_business_price_check_360('de')
    })

    /*it('Image page assertions packs',function()
    {
        const imp = new imagePackInImagePage()
        const ip = new ImagePage()
        imp.login_packUser('de')
        ip.imagePage_visit_RM('de')
        imp.imagePage_license_personalUse_pack('de')
        imp.imagePage_license_presentation_pack('de')
        imp.imagePage_license_website_pack('de')
        imp.imagePage_license_Marketing_package_Small_business_pack('de')
        imp.imagePage_license_Marketing_package_Large_business_pack('de')
    })*/

    /*17 Restriction test cases in image page are written below
    Parameters passing with flag=0 for licenses to show
    Parameters passing with flag=1 for licenses to show and disable
    Parameters passing with flag=2 for licenses to hide
    */

    it('Image page restrictions logic 1',function()
    {
        const ip = new ImagePage()
        ip.imagePage_visit_Restriction_Logic_1('de')
        ip.imagePage_personalUse_Restriction(1)
        ip.imagePage_presentation_Restriction(0)
        ip.imagePage_license_Editorial_presentation_Restriction(2)
        ip.imagePage_website_Restriction(0)
        ip.imagePage_license_Editorial_Website_Restriction(2)
        ip.imagePage_magazine_Restriction(0)
        ip.imagePage_marketingSmallBusiness_Restriction(0)
        ip.imagePage_marketingLargeBusiness_Restriction(0)
        ip.imagePage_license_personalUse_Editorial_RF_Restriction(2)
        ip.imagePage_license_presentation_Editorial_RF_Restriction(2)
        ip.imagePage_license_website_Editorial_RF_Restriction(2)
        ip.imagePage_license_magazine_Editorial_RF_Restriction(2)
    })

    it('Image page restrictions logic 2',function()
    {
        const ip = new ImagePage()
        ip.imagePage_visit_Restriction_Logic_2('de')
        ip.imagePage_personalUse_Restriction(0)
        ip.imagePage_website_Restriction(2)
        ip.imagePage_license_Editorial_Website_Restriction(0)
        ip.imagePage_presentation_Restriction(2)
        ip.imagePage_license_Editorial_presentation_Restriction(0)
        ip.imagePage_license_Editorial_magazine_Restriction(0)
        ip.imagePage_marketingSmallBusiness_Restriction(1)
        ip.imagePage_marketingLargeBusiness_Restriction(1)
        ip.imagePage_license_personalUse_Editorial_RF_Restriction(2)
        ip.imagePage_license_presentation_Editorial_RF_Restriction(2)
        ip.imagePage_license_website_Editorial_RF_Restriction(2)
        ip.imagePage_license_magazine_Editorial_RF_Restriction(2)
    })

    it('Image page restrictions logic 3',function()
    {
        const ip = new ImagePage()
        ip.imagePage_visit_Restriction_Logic_3('de')
        ip.imagePage_personalUse_Restriction(0)
        ip.imagePage_website_Restriction(0)
        ip.imagePage_license_Editorial_Website_Restriction(2)
        ip.imagePage_presentation_Restriction(0)
        ip.imagePage_license_Editorial_presentation_Restriction(2)
        ip.imagePage_magazine_Restriction(0)
        ip.imagePage_marketingSmallBusiness_Restriction(0)
        ip.imagePage_marketingLargeBusiness_Restriction(0)
        ip.imagePage_license_personalUse_Editorial_RF_Restriction(2)
        ip.imagePage_license_presentation_Editorial_RF_Restriction(2)
        ip.imagePage_license_website_Editorial_RF_Restriction(2)
        ip.imagePage_license_magazine_Editorial_RF_Restriction(2)
    })

    it('Image page restrictions logic 4',function()
    {
        const ip = new ImagePage()
        ip.imagePage_visit_Restriction_Logic_4('de')
        ip.imagePage_personalUse_Restriction(0)
        ip.imagePage_website_Restriction(0)
        ip.imagePage_license_Editorial_Website_Restriction(2)
        ip.imagePage_presentation_Restriction(0)
        ip.imagePage_license_Editorial_presentation_Restriction(2)
        ip.imagePage_magazine_Restriction(1)
        ip.imagePage_marketingSmallBusiness_Restriction(0)
        ip.imagePage_marketingLargeBusiness_Restriction(0)
        ip.imagePage_license_personalUse_Editorial_RF_Restriction(2)
        ip.imagePage_license_presentation_Editorial_RF_Restriction(2)
        ip.imagePage_license_website_Editorial_RF_Restriction(2)
        ip.imagePage_license_magazine_Editorial_RF_Restriction(2)
    })

    it('Image page restrictions logic 5',function()
    {
        const ip = new ImagePage()
        ip.imagePage_visit_Restriction_Logic_5('de')
        ip.imagePage_personalUse_Restriction(1)
        ip.imagePage_website_Restriction(2)
        ip.imagePage_license_Editorial_Website_Restriction(0)
        ip.imagePage_presentation_Restriction(2)
        ip.imagePage_license_Editorial_presentation_Restriction(0)
        ip.imagePage_license_Editorial_magazine_Restriction(0)
        ip.imagePage_marketingSmallBusiness_Restriction(1)
        ip.imagePage_marketingLargeBusiness_Restriction(1)
        ip.imagePage_license_personalUse_Editorial_RF_Restriction(2)
        ip.imagePage_license_presentation_Editorial_RF_Restriction(2)
        ip.imagePage_license_website_Editorial_RF_Restriction(2)
        ip.imagePage_license_magazine_Editorial_RF_Restriction(2)
    })

    it('Image page restrictions logic 6',function()
    {
        const ip = new ImagePage()
        ip.imagePage_visit_Restriction_Logic_6('de')
        ip.imagePage_personalUse_Restriction(1)
        ip.imagePage_website_Restriction(0)
        ip.imagePage_license_Editorial_Website_Restriction(2)
        ip.imagePage_presentation_Restriction(0)
        ip.imagePage_license_Editorial_presentation_Restriction(2)
        ip.imagePage_magazine_Restriction(0)
        ip.imagePage_marketingSmallBusiness_Restriction(0)
        ip.imagePage_marketingLargeBusiness_Restriction(0)
        ip.imagePage_license_personalUse_Editorial_RF_Restriction(2)
        ip.imagePage_license_presentation_Editorial_RF_Restriction(2)
        ip.imagePage_license_website_Editorial_RF_Restriction(2)
        ip.imagePage_license_magazine_Editorial_RF_Restriction(2)
    })

    it('Image page restrictions logic 7',function()
    {
        const ip = new ImagePage()
        ip.imagePage_visit_Restriction_Logic_7('de')
        ip.imagePage_personalUse_Restriction(1)
        ip.imagePage_website_Restriction(0)
        ip.imagePage_license_Editorial_Website_Restriction(2)
        ip.imagePage_presentation_Restriction(0)
        ip.imagePage_license_Editorial_presentation_Restriction(2)
        ip.imagePage_magazine_Restriction(1)
        ip.imagePage_marketingSmallBusiness_Restriction(0)
        ip.imagePage_marketingLargeBusiness_Restriction(0)
        ip.imagePage_license_personalUse_Editorial_RF_Restriction(2)
        ip.imagePage_license_presentation_Editorial_RF_Restriction(2)
        ip.imagePage_license_website_Editorial_RF_Restriction(2)
        ip.imagePage_license_magazine_Editorial_RF_Restriction(2)
    })

    it('Image page restrictions logic 8',function()
    {
        const ip = new ImagePage()
        ip.imagePage_visit_Restriction_Logic_8('de')
        ip.imagePage_license_PersonalUse_Editorial_Restriction(0)
        ip.imagePage_presentation_Restriction(2)
        ip.imagePage_license_Editorial_presentation_Restriction(0)
        ip.imagePage_website_Restriction(2)
        ip.imagePage_license_Editorial_Website_Restriction(0)
        ip.imagePage_license_Editorial_magazine_Restriction(0)
        ip.imagePage_marketingSmallBusiness_Restriction(1)
        ip.imagePage_marketingLargeBusiness_Restriction(1)
        ip.imagePage_license_personalUse_Editorial_RF_Restriction(2)
        ip.imagePage_license_presentation_Editorial_RF_Restriction(2)
        ip.imagePage_license_website_Editorial_RF_Restriction(2)
        ip.imagePage_license_magazine_Editorial_RF_Restriction(2)
    })

    it('Image page restrictions logic 9',function()
    {
        const ip = new ImagePage()
        ip.imagePage_visit_Restriction_Logic_9('de')
        ip.imagePage_personalUse_Restriction(0)
        ip.imagePage_presentation_Restriction(1)
        ip.imagePage_license_Editorial_presentation_Restriction(2)
        ip.imagePage_website_Restriction(1)
        ip.imagePage_license_Editorial_Website_Restriction(2)
        ip.imagePage_magazine_Restriction(1)
        ip.imagePage_marketingSmallBusiness_Restriction(1)
        ip.imagePage_marketingLargeBusiness_Restriction(1)
        ip.imagePage_license_personalUse_Editorial_RF_Restriction(2)
        ip.imagePage_license_presentation_Editorial_RF_Restriction(2)
        ip.imagePage_license_website_Editorial_RF_Restriction(2)
        ip.imagePage_license_magazine_Editorial_RF_Restriction(2)
    })

    it('Image page restrictions logic 10',function()
    {
        const ip = new ImagePage()
        ip.imagePage_visit_Restriction_Logic_10('de')
        ip.imagePage_personalUse_Restriction(0)
        ip.imagePage_presentation_Restriction(0)
        ip.imagePage_license_Editorial_presentation_Restriction(2)
        ip.imagePage_website_Restriction(0)
        ip.imagePage_license_Editorial_Website_Restriction(2)
        ip.imagePage_magazine_Restriction(1)
        ip.imagePage_marketingSmallBusiness_Restriction(0)
        ip.imagePage_marketingLargeBusiness_Restriction(0)
        ip.imagePage_license_personalUse_Editorial_RF_Restriction(2)
        ip.imagePage_license_presentation_Editorial_RF_Restriction(2)
        ip.imagePage_license_website_Editorial_RF_Restriction(2)
        ip.imagePage_license_magazine_Editorial_RF_Restriction(2)
    })

    it('Image page restrictions logic 11',function()
    {
        const ip = new ImagePage()
        ip.imagePage_visit_Restriction_Logic_11('de')
        ip.imagePage_personalUse_Restriction(1)
        ip.imagePage_presentation_Restriction(2)
        ip.imagePage_license_Editorial_presentation_Restriction(0)
        ip.imagePage_website_Restriction(2)
        ip.imagePage_license_Editorial_Website_Restriction(0)
        ip.imagePage_license_Editorial_magazine_Restriction(0)
        ip.imagePage_marketingSmallBusiness_Restriction(1)
        ip.imagePage_marketingLargeBusiness_Restriction(1)
        ip.imagePage_license_personalUse_Editorial_RF_Restriction(2)
        ip.imagePage_license_presentation_Editorial_RF_Restriction(2)
        ip.imagePage_license_website_Editorial_RF_Restriction(2)
        ip.imagePage_license_magazine_Editorial_RF_Restriction(2)
    })

    it('Image page restrictions logic 12',function()
    {
        const ip = new ImagePage()
        ip.imagePage_visit_Restriction_Logic_12('de')
        ip.imagePage_personalUse_Restriction(1)
        ip.imagePage_presentation_Restriction(0)
        ip.imagePage_license_Editorial_presentation_Restriction(2)
        ip.imagePage_website_Restriction(0)
        ip.imagePage_license_Editorial_Website_Restriction(2)
        ip.imagePage_magazine_Restriction(1)
        ip.imagePage_marketingSmallBusiness_Restriction(0)
        ip.imagePage_marketingLargeBusiness_Restriction(0)
        ip.imagePage_license_personalUse_Editorial_RF_Restriction(2)
        ip.imagePage_license_presentation_Editorial_RF_Restriction(2)
        ip.imagePage_license_website_Editorial_RF_Restriction(2)
        ip.imagePage_license_magazine_Editorial_RF_Restriction(2)
    })

    it('Image page restrictions logic 13',function()
    {
        const ip = new ImagePage()
        ip.imagePage_visit_Restriction_Logic_13('de')
        ip.imagePage_personalUse_Restriction(1)
        ip.imagePage_presentation_Restriction(1)
        ip.imagePage_license_Editorial_presentation_Restriction(2)
        ip.imagePage_website_Restriction(1)
        ip.imagePage_license_Editorial_Website_Restriction(2)
        ip.imagePage_magazine_Restriction(1)
        ip.imagePage_marketingSmallBusiness_Restriction(1)
        ip.imagePage_marketingLargeBusiness_Restriction(1)
        ip.imagePage_license_personalUse_Editorial_RF_Restriction(2)
        ip.imagePage_license_presentation_Editorial_RF_Restriction(2)
        ip.imagePage_license_website_Editorial_RF_Restriction(2)
        ip.imagePage_license_magazine_Editorial_RF_Restriction(2)
    })

    it('Image page restrictions logic 14',function()
    {
        const ip = new ImagePage()
        ip.imagePage_visit_Restriction_Logic_14('de')
        ip.imagePage_personalUse_Restriction(0)
        ip.imagePage_presentation_Restriction(1)
        ip.imagePage_license_Editorial_presentation_Restriction(2)
        ip.imagePage_website_Restriction(1)
        ip.imagePage_license_Editorial_Website_Restriction(2)
        ip.imagePage_magazine_Restriction(1)
        ip.imagePage_marketingSmallBusiness_Restriction(1)
        ip.imagePage_marketingLargeBusiness_Restriction(1)
        ip.imagePage_license_personalUse_Editorial_RF_Restriction(2)
        ip.imagePage_license_presentation_Editorial_RF_Restriction(2)
        ip.imagePage_license_website_Editorial_RF_Restriction(2)
        ip.imagePage_license_magazine_Editorial_RF_Restriction(2)
    })

    it('Image page restrictions logic 15',function()
    {
        const ip = new ImagePage()
        ip.imagePage_visit_Restriction_Logic_15('de')
        ip.imagePage_personalUse_Restriction(1)
        ip.imagePage_presentation_Restriction(1)
        ip.imagePage_license_Editorial_presentation_Restriction(2)
        ip.imagePage_website_Restriction(1)
        ip.imagePage_license_Editorial_Website_Restriction(2)
        ip.imagePage_magazine_Restriction(1)
        ip.imagePage_marketingSmallBusiness_Restriction(1)
        ip.imagePage_marketingLargeBusiness_Restriction(1)
        ip.imagePage_license_personalUse_Editorial_RF_Restriction(2)
        ip.imagePage_license_presentation_Editorial_RF_Restriction(2)
        ip.imagePage_license_website_Editorial_RF_Restriction(2)
        ip.imagePage_license_magazine_Editorial_RF_Restriction(2)
    })

    it('Image page restrictions logic 16',function()
    {
        const ip = new ImagePage()
        ip.imagePage_visit_Restriction_Logic_16('de')
        ip.imagePage_personalUse_Restriction(2)
        ip.imagePage_license_PersonalUse_Editorial_Restriction(0)
        ip.imagePage_presentation_Restriction(2)
        ip.imagePage_license_Editorial_presentation_Restriction(0)
        ip.imagePage_website_Restriction(2)
        ip.imagePage_license_Editorial_Website_Restriction(0)
        ip.imagePage_magazine_Restriction(2)
        ip.imagePage_license_Editorial_magazine_Restriction(0)
        ip.imagePage_license_marketingSmallBusiness_Editorial_Restriction(0)
        ip.imagePage_license_marketingLargeBusiness_Editorial_Restriction(0)
    })

    it('Image page restrictions logic 17',function()
    {
        const ip = new ImagePage()
        ip.imagePage_visit_Restriction_Logic_17('de')
        ip.imagePage_personalUse_Restriction(2)
        ip.imagePage_license_personalUse_Editorial_RF_Restriction(0)
        ip.imagePage_presentation_Restriction(2)
        ip.imagePage_license_presentation_Editorial_RF_Restriction(0)
        ip.imagePage_website_Restriction(2)
        ip.imagePage_license_website_Editorial_RF_Restriction(0)
        ip.imagePage_magazine_Restriction(2)
        ip.imagePage_license_magazine_Editorial_RF_Restriction(0)
        ip.imagePage_license_marketingSmallBusiness_Editorial_Restriction(0)
        ip.imagePage_license_marketingLargeBusiness_Editorial_Restriction(0)
    })
})