describe('Standard License',function() 
{
    //url format : licensing/standard/{currency}/{domain}
    it('Standard License GBP : en ', (done) => {
        cy.request(Cypress.env('baseurl')+'/microservices/licenses/managelicenses.asmx/GetStandardLicenses?currency=gbp&langcode=en').as('comments')
        cy.get('@comments').should((response) => {
            expect(response.status).to.eq(200);
            expect(response.body.success).to.equal(true);
            expect(response.body.data[0]).to.deep.equals({
              "licenseId": "573b1edc-f841-4e2e-8c34-33e462b5eb39",
              "title": "Personal use",
              "shortDescription": "Personal prints, cards and gifts",
              "longDescription": "Personal prints, cards and gifts, or reference for artists.  Non-commercial use only, not for resale.",
              "price": 9.99,
              "currency": "GBP",
              "usageRestrictions": "99z",
              "licenseType": "rm",
              "productType": "image",
              "pictureType": "photograph,illustration",
              "isEditorial": false,
              "orderBy": 0,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[1]).to.deep.equal({
              "licenseId": "a664be02-794a-449b-a6da-63d7235f3085",
              "title": "Personal use",
              "shortDescription": "Personal prints, cards and gifts",
              "longDescription": "Personal prints, cards and gifts, or reference for artists.  Non-commercial use only, not for resale.",
              "price": 9.99,
              "currency": "GBP",
              "usageRestrictions": "99z",
              "licenseType": "rf",
              "productType": "image",
              "pictureType": "photograph,illustration",
              "isEditorial": false,
              "orderBy": 0,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""        
            });
            expect(response.body.data[2]).to.deep.equal({
              "licenseId": "e1b8550c-d6d3-4e5a-9b71-880ddf78a65a",
              "title": "Presentation or newsletters",
              "shortDescription": "Use in a presentation/talk (eg,Powerpoint and Keynote) or in a newsletter.",
              "longDescription": "Use in a presentation/talk (eg,Powerpoint and Keynote) or in a newsletter.",
              "price": 9.99,
              "currency": "GBP",
              "usageRestrictions": "99y",
              "licenseType": "rm",
              "productType": "image",
              "pictureType": "photograph,illustration",
              "isEditorial": false,
              "orderBy": 1,
              "hasEditorialLicense": true,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[3]).to.deep.equal({
              "licenseId": "6b1ca3d6-9d5f-4e60-ac0a-829bba8bd9f8",
              "title": "Presentation or newsletters",
              "shortDescription": "Use in a presentation/talk (eg,Powerpoint and Keynote) or in an editorial newsletter.",
              "longDescription": "Use in a presentation/talk (eg,Powerpoint and Keynote) or in an editorial newsletter.",
              "price": 9.99,
              "currency": "GBP",
              "usageRestrictions": "2e",
              "licenseType": "rm",
              "productType": "image",
              "pictureType": "photograph,illustration",
              "isEditorial": true,
              "orderBy": 1,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[4]).to.deep.equal({
              "licenseId": "a184757e-8c14-4089-b679-311548733c75",
              "title": "Website or social media site",
              "shortDescription": "Use in a single website or Blog forever or a social media site for 3 months boosted post and archive forever (excludes any other advertising).",
              "longDescription": "Use in a single website or Blog forever or a social media site for 3 months boosted post and archive forever (excludes any other advertising).",
              "price": 249.99,
              "currency": "GBP",
              "usageRestrictions": "2a,2c,2d,2e,2g,99y,99z",
              "licenseType": "rm",
              "productType": "image",
              "pictureType": "360",
              "isEditorial": false,
              "orderBy": 1,
              "hasEditorialLicense": true,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[5]).to.deep.equal({
              "licenseId": "97937d7a-e8b3-44ff-b080-41cdebb71e21",
              "title": "Editorial Website",
              "shortDescription": "Use in a single editorial website or Blog forever (excludes advertising).",
              "longDescription": "Use in a single editorial website or Blog forever (excludes advertising).",
              "price": 249.99,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rm",
              "productType": "image",
              "pictureType": "360",
              "isEditorial": true,
              "orderBy": 1,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[6]).to.deep.equal({
              "licenseId": "29d6ed33-649f-428d-8478-d102c06258f9",
              "title": "Presentation or newsletters",
              "shortDescription": "Use in a presentation/talk (eg,Powerpoint and Keynote) or in a newsletter.",
              "longDescription": "Use in a presentation/talk (eg,Powerpoint and Keynote) or in a newsletter.",
              "price": 9.99,
              "currency": "GBP",
              "usageRestrictions": "99y",
              "licenseType": "rf",
              "productType": "image",
              "pictureType": "photograph,illustration",
              "isEditorial": false,
              "orderBy": 1,
              "hasEditorialLicense": true,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[7]).to.deep.equal({
              "licenseId": "f09ea294-376e-47d5-b5d8-fa2af296a696",
              "title": "Royalty-free – JPEG and vector",
              "shortDescription": "All rights, all media, worldwide in perpetuity.",
              "longDescription": "All rights, all media, worldwide in perpetuity.",
              "price": 9.99,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rf",
              "productType": "image",
              "pictureType": "vector",
              "isEditorial": false,
              "orderBy": 1,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[8]).to.deep.equal({
              "licenseId": "6b1ca3d6-9d5f-4e60-ac0a-829bba8bd9f8",
              "title": "Presentation or newsletters",
              "shortDescription": "Use in a presentation/talk (eg,Powerpoint and Keynote) or in an editorial newsletter.",
              "longDescription": "Use in a presentation/talk (eg,Powerpoint and Keynote) or in an editorial newsletter.",
              "price": 9.99,
              "currency": "GBP",
              "usageRestrictions": "2e",
              "licenseType": "rf",
              "productType": "image",
              "pictureType": "photograph,illustration",
              "isEditorial": true,
              "orderBy": 1,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[9]).to.deep.equal({
              "licenseId": "e31dc3ef-2dba-449a-8bb3-a66a63948656",
              "title": "Website or social media site",
              "shortDescription": "Use in a single website or Blog forever or a social media site for 3 months boosted post and archive forever (excludes any other advertising).",
              "longDescription": "Use in a single website or Blog forever or a social media site for 3 months boosted post and archive forever (excludes any other advertising).",
              "price": 249.99,
              "currency": "GBP",
              "usageRestrictions": "2a,2c,2d,2e,2g,99y,99z",
              "licenseType": "rf",
              "productType": "image",
              "pictureType": "360",
              "isEditorial": false,
              "orderBy": 1,
              "hasEditorialLicense": true,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[10]).to.deep.equal({
              "licenseId": "97937d7a-e8b3-44ff-b080-41cdebb71e21",
              "title": "Editorial Website",
              "shortDescription": "Use in a single editorial website or Blog forever (excludes advertising).",
              "longDescription": "Use in a single editorial website or Blog forever (excludes advertising).",
              "price": 249.99,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rf",
              "productType": "image",
              "pictureType": "360",
              "isEditorial": true,
              "orderBy": 1,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[11]).to.deep.equal({
              "licenseId": "ba0f3994-44bc-4b81-ba09-5a28c595af22",
              "title": "Website",
              "shortDescription": "Use in a single website, app, social media or blog (excludes advertising), worldwide.",
              "longDescription": "Use in a single website, app, social media or blog (excludes advertising), worldwide.",
              "price": 29.99,
              "currency": "GBP",
              "usageRestrictions": "99y",
              "licenseType": "rm",
              "productType": "image",
              "pictureType": "photograph,illustration",
              "isEditorial": false,
              "orderBy": 2,
              "hasEditorialLicense": true,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[12]).to.deep.equal({
              "licenseId": "19384362-4b33-415b-9738-a26ae0b00f41",
              "title": "Editorial website",
              "shortDescription": "Editorial: Use in a single website, app, social media or blog (excludes advertising), worldwide.",
              "longDescription": "Editorial: Use in a single website, app, social media or blog (excludes advertising), worldwide.",
              "price": 29.99,
              "currency": "GBP",
              "usageRestrictions": "2e",
              "licenseType": "rm",
              "productType": "image",
              "pictureType": "photograph,illustration",
              "isEditorial": true,
              "orderBy": 2,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[13]).to.deep.equal({
              "licenseId": "8ac2372d-5ca1-4599-8c26-d33d2cfeb8cf",
              "title": "VR or game apps",
              "shortDescription": "Use in a single native commercial VR, corporate promotional or mobile game app.",
              "longDescription": "Use in a single native commercial VR, corporate promotional or mobile game app.",
              "price": 299.99,
              "currency": "GBP",
              "usageRestrictions": "2a,2b,2c,2d,2e,2g,99y,99z",
              "licenseType": "rm",
              "productType": "image",
              "pictureType": "360",
              "isEditorial": false,
              "orderBy": 2,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[14]).to.deep.equal({
              "licenseId": "6a1d7471-6cc6-4b3d-818e-fffe26bd573e",
              "title": "Website",
              "shortDescription": "Use in a single website, app, social media or blog (excludes advertising), worldwide.",
              "longDescription": "Use in a single website, app, social media or blog (excludes advertising), worldwide.",
              "price": 29.99,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rf",
              "productType": "image",
              "pictureType": "photograph,illustration",
              "isEditorial": false,
              "orderBy": 2,
              "hasEditorialLicense": true,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[15]).to.deep.equal({
              "licenseId": "19384362-4b33-415b-9738-a26ae0b00f41",
              "title": "Editorial website",
              "shortDescription": "Editorial: Use in a single website, app, social media or blog (excludes advertising), worldwide.",
              "longDescription": "Editorial: Use in a single website, app, social media or blog (excludes advertising), worldwide.",
              "price": 29.99,
              "currency": "GBP",
              "usageRestrictions": "2e",
              "licenseType": "rf",
              "productType": "image",
              "pictureType": "photograph,illustration",
              "isEditorial": true,
              "orderBy": 2,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[16]).to.deep.equal({
              "licenseId": "648fe747-9928-47c4-8fda-e8156db78ec7",
              "title": "VR or game apps",
              "shortDescription": "Use in a single native commercial VR, corporate promotional or mobile game app.",
              "longDescription": "Use in a single native commercial VR, corporate promotional or mobile game app.",
              "price": 299.99,
              "currency": "GBP",
              "usageRestrictions": "2a,2b,2c,2d,2e,2g,99y,99z",
              "licenseType": "rf",
              "productType": "image",
              "pictureType": "360",
              "isEditorial": false,
              "orderBy": 2,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": true,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[17]).to.deep.equal({
              "licenseId": "782d55ce-6c5c-4ac9-9919-e89b88bf76ad",
              "title": "Magazines and books",
              "shortDescription": "Use in a single magazine or book (print and/or digital), inside use, 2,500 circulation, worldwide (excludes advertising).",
              "longDescription": "Use in a single magazine or book (print and/or digital), inside use, 2,500 circulation, worldwide (excludes advertising).",
              "price": 39.99,
              "currency": "GBP",
              "usageRestrictions": "2e",
              "licenseType": "rm",
              "productType": "image",
              "pictureType": "photograph,illustration",
              "isEditorial": false,
              "orderBy": 3,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[18]).to.deep.equal({
              "licenseId": "cdee862e-01be-46ae-8910-357be026a5e2",
              "title": "Digital publishing",
              "shortDescription": "Use inside a single educational or retail publishing digital product for 10 years.",
              "longDescription": "Use inside a single educational or retail publishing digital product for 10 years.",
              "price": 299.99,
              "currency": "GBP",
              "usageRestrictions": "2e",
              "licenseType": "rm",
              "productType": "image",
              "pictureType": "360",
              "isEditorial": false,
              "orderBy": 3,
              "hasEditorialLicense": true,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[19]).to.deep.equal({
              "licenseId": "7dfe352c-b426-4864-a9ad-99a1ce2baafc",
              "title": "Digital publishing",
              "shortDescription": "Use inside a single educational digital product for 10 years.",
              "longDescription": "Use inside a single educational digital product for 10 years.",
              "price": 299.99,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rm",
              "productType": "image",
              "pictureType": "360",
              "isEditorial": true,
              "orderBy": 3,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[20]).to.deep.equal({
              "licenseId": "caa1f837-d985-4e49-bb57-4b74860c5fe8",
              "title": "Magazines and books",
              "shortDescription": "Use in a single magazine or book (print and/or digital), inside use, 2,500 circulation, worldwide (excludes advertising).",
              "longDescription": "Use in a single magazine or book (print and/or digital), inside use, 2,500 circulation, worldwide (excludes advertising).",
              "price": 39.99,
              "currency": "GBP",
              "usageRestrictions": "2e",
              "licenseType": "rf",
              "productType": "image",
              "pictureType": "photograph,illustration",
              "isEditorial": false,
              "orderBy": 3,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[21]).to.deep.equal({
              "licenseId": "bdc87ff7-4678-4073-94ed-6667873aeec0",
              "title": "Digital publishing",
              "shortDescription": "Use inside a single educational or retail publishing digital product for 10 years.",
              "longDescription": "Use inside a single educational or retail publishing digital product for 10 years.",
              "price": 299.99,
              "currency": "GBP",
              "usageRestrictions": "2e",
              "licenseType": "rf",
              "productType": "image",
              "pictureType": "360",
              "isEditorial": false,
              "orderBy": 3,
              "hasEditorialLicense": true,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[22]).to.deep.equal({
              "licenseId": "7dfe352c-b426-4864-a9ad-99a1ce2baafc",
              "title": "Digital publishing",
              "shortDescription": "Use inside a single educational digital product for 10 years.",
              "longDescription": "Use inside a single educational digital product for 10 years.",
              "price": 299.99,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rf",
              "productType": "image",
              "pictureType": "360",
              "isEditorial": true,
              "orderBy": 3,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[23]).to.deep.equal({
              "licenseId": "d60b3342-07f9-44f5-9b25-7c3e30fc45a1",
              "title": "TV program",
              "shortDescription": "For use in a single TV program, all media, forever.",
              "longDescription": "For use in a single TV program, all media, forever.",
              "price": 349.99,
              "currency": "GBP",
              "usageRestrictions": "2e",
              "licenseType": "rm",
              "productType": "image",
              "pictureType": "360",
              "isEditorial": false,
              "orderBy": 4,
              "hasEditorialLicense": true,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[24]).to.deep.equal({
              "licenseId": "97f4ab1a-acc5-49ff-abbc-9e340ffe594c",
              "title": "TV programme",
              "shortDescription": "For editorial use in a single TV programme, forever.",
              "longDescription": "For editorial use in a single TV programme, forever.",
              "price": 349.99,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rm",
              "productType": "image",
              "pictureType": "360",
              "isEditorial": true,
              "orderBy": 4,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });

            expect(response.body.data[25]).to.deep.equal({
              "licenseId": "38e76993-1946-4246-97a2-8371cdf0a237",
              "title": "TV program",
              "shortDescription": "For use in a single TV program, all media, forever.",
              "longDescription": "For use in a single TV program, all media, forever.",
              "price": 349.99,
              "currency": "GBP",
              "usageRestrictions": "2e",
              "licenseType": "rf",
              "productType": "image",
              "pictureType": "360",
              "isEditorial": false,
              "orderBy": 4,
              "hasEditorialLicense": true,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[26]).to.deep.equal({
              "licenseId": "97f4ab1a-acc5-49ff-abbc-9e340ffe594c",
              "title": "TV programme",
              "shortDescription": "For editorial use in a single TV programme, forever.",
              "longDescription": "For editorial use in a single TV programme, forever.",
              "price": 349.99,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rf",
              "productType": "image",
              "pictureType": "360",
              "isEditorial": true,
              "orderBy": 4,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[27]).to.deep.equal({
              "licenseId": "c3c1e2ed-043a-48d3-98a8-1016cf410cb2",
              "title": "Marketing package",
              "shortDescription": "Use in a single marketing campaign, worldwide (excludes advertising). This package is for a marketing campaign for promoting a business.",
              "longDescription": "Use in a single marketing campaign, worldwide (excludes advertising). This package is for a marketing campaign for promoting a business.",
              "price": 149.99,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rm",
              "productType": "image",
              "pictureType": "photograph,illustration",
              "isEditorial": false,
              "orderBy": 5,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[28]).to.deep.equal({
              "licenseId": "4fde0600-e161-48e0-8980-8aa1d757e29d",
              "title": "Marketing package",
              "shortDescription": "Use in a single marketing campaign, worldwide (excludes advertising). This package is for a marketing campaign for promoting a business.",
              "longDescription": "Use in a single marketing campaign, worldwide (excludes advertising). This package is for a marketing campaign for promoting a business.",
              "price": 149.99,
              "currency": "GBP",
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rf",
              "productType": "image",
              "pictureType": "photograph,illustration",
              "isEditorial": false,
              "orderBy": 5,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": true,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[29]).to.deep.equal({
              "licenseId": "628087cb-91a8-4ba9-ab52-8c5647a041da",
              "title": "Marketing package",
              "shortDescription": "Use in a single marketing campaign, worldwide (excludes advertising). This package is for a marketing campaign for promoting a business.",
              "longDescription": "Use in a single marketing campaign, worldwide (excludes advertising). This package is for a marketing campaign for promoting a business.",
              "price": 399.99,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rm",
              "productType": "image",
              "pictureType": "360",
              "isEditorial": false,
              "orderBy": 6,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[30]).to.deep.equal({
              "licenseId": "e162a13c-40ae-4562-a4a2-4bad5578539f",
              "title": "Marketing package",
              "shortDescription": "Use in a single marketing campaign, worldwide (excludes advertising). This package is for a marketing campaign for promoting a business.",
              "longDescription": "Use in a single marketing campaign, worldwide (excludes advertising). This package is for a marketing campaign for promoting a business.",
              "price": 399.99,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rf",
              "productType": "image",
              "pictureType": "360",
              "isEditorial": false,
              "orderBy": 6,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": true,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[31]).to.deep.equal({
              "licenseId": "5d7f2aab-a7f8-424b-90fc-bd2e2e47af04",
              "title": "Royalty-free license",
              "shortDescription": "For any permitted use, forever.",
              "longDescription": "For any permitted use, forever.",
              "price": 450.00,
              "currency": "GBP",
              "usageRestrictions": "2e",
              "licenseType": "rf",
              "productType": "image",
              "pictureType": "360",
              "isEditorial": false,
              "orderBy": 7,
              "hasEditorialLicense": true,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[32]).to.deep.equal({
              "licenseId": "54edd551-949c-423d-9002-c630ab6f72fe",
              "title": "Editorial Royalty Free License",
              "shortDescription": "For any permitted editorial use, forever.",
              "longDescription": "For any permitted editorial use, forever.",
              "price": 450,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rf",
              "productType": "image",
              "pictureType": "360",
              "isEditorial": true,
              "orderBy": 7,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "",
              "resolutionType": ""
            });
            expect(response.body.data[33]).to.deep.equal({
              "licenseId": "9e960f63-1974-4be7-9a48-4040a9769a37",
              "title": "HD - Standard",
              "shortDescription": "Web & social media – single project",
              "longDescription": "Web & social media – single project",
              "price": 48,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rf",
              "productType": "video",
              "pictureType": "",
              "isEditorial": false,
              "orderBy": 0,
              "hasEditorialLicense": true,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "standard",
              "resolutionType": "hd"
            });
            expect(response.body.data[34]).to.deep.equal({
              "licenseId": "225be598-5969-4804-af7b-850b50ea9395",
              "title": "HD - Standard",
              "shortDescription": "Web & social media – single project",
              "longDescription": "Web & social media – single project. Editorial use only",
              "price": 48,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rf",
              "productType": "video",
              "pictureType": "",
              "isEditorial": true,
              "orderBy": 0,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "standard",
              "resolutionType": "hd"
            });
            expect(response.body.data[35]).to.deep.equal({
              "licenseId": "ea5a9792-6311-4b82-9921-e8fbd7875336",
              "title": "4K - Standard",
              "shortDescription": "Web & social media – single project",
              "longDescription": "Web & social media – single project",
              "price": 73,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rf",
              "productType": "video",
              "pictureType": "",
              "isEditorial": false,
              "orderBy": 1,
              "hasEditorialLicense": true,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "standard",
              "resolutionType": "4k"
            });

            expect(response.body.data[36]).to.deep.equal({
              "licenseId": "189912fd-3f8d-4764-90b7-35a69aada95d",
              "title": "4K - Standard",
              "shortDescription": "Web & social media – single project",
              "longDescription": "Web & social media – single project. Editorial use only",
              "price": 73.00,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rf",
              "productType": "video",
              "pictureType": "",
              "isEditorial": true,
              "orderBy": 1,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "standard",
              "resolutionType": "4k"
            });
            expect(response.body.data[37]).to.deep.equal({
              "licenseId": "481eec0b-d998-48dc-ac50-ad1053c9ee19",
              "title": "HD - Enhanced",
              "shortDescription": "Worry free all-media use – single project",
              "longDescription": "Worry free all-media use – single project",
              "price": 135.00,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rf",
              "productType": "video",
              "pictureType": "",
              "isEditorial": false,
              "orderBy": 2,
              "hasEditorialLicense": true,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "enhanced",
              "resolutionType": "hd"
            });
            expect(response.body.data[38]).to.deep.equal({
              "licenseId": "59e175a2-299d-4a41-ae90-452362ae4b92",
              "title": "HD - Enhanced",
              "shortDescription": "Worry free all-media use – single project",
              "longDescription": "Worry free all-media use – single project. Editorial use only.",
              "price": 135.00,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rf",
              "productType": "video",
              "pictureType": "",
              "isEditorial": true,
              "orderBy": 2,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "enhanced",
              "resolutionType": "hd"
            });
            expect(response.body.data[39]).to.deep.equal({
              "licenseId": "dfde6cf5-a518-4e48-a9d5-838f46fa6a60",
              "title": "4K - Enhanced",
              "shortDescription": "Worry free all-media use – single project",
              "longDescription": "Worry free all-media use – single project",
              "price": 200.00,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rf",
              "productType": "video",
              "pictureType": "",
              "isEditorial": false,
              "orderBy": 3,
              "hasEditorialLicense": true,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "enhanced",
              "resolutionType": "4k"
            });
            expect(response.body.data[40]).to.deep.equal({
              "licenseId": "1e8cf27c-fe15-42da-8e97-e74b77c37a58",
              "title": "4K - Enhanced",
              "shortDescription": "Worry free all-media use – single project",
              "longDescription": "Worry free all-media use – single project. Editorial use only.",
              "price": 200.00,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rf",
              "productType": "video",
              "pictureType": "",
              "isEditorial": true,
              "orderBy": 3,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "enhanced",
              "resolutionType": "4k"
            });
            expect(response.body.data[41]).to.deep.equal({
              "licenseId": "54038758-d373-4ad4-9c9a-1cd9789916d0",
              "title": "HD - Full Royalty Free (RF)",
              "shortDescription": "Freedom for all uses forever – multiple projects",
              "longDescription": "Freedom for all uses forever – multiple projects",
              "price": 245.00,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rf",
              "productType": "video",
              "pictureType": "",
              "isEditorial": false,
              "orderBy": 4,
              "hasEditorialLicense": true,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "fullRoyaltyfree",
              "resolutionType": "hd"
            });
            expect(response.body.data[42]).to.deep.equal({
              "licenseId": "6e3a7c1c-9e37-48ff-8741-902b833d6a46",
              "title": "HD - Full Royalty Free (RF)",
              "shortDescription": "Freedom for all uses forever – multiple projects",
              "longDescription": "Freedom for all uses forever – multiple projects. Editorial use only.",
              "price": 245.00,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rf",
              "productType": "video",
              "pictureType": "",
              "isEditorial": true,
              "orderBy": 4,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "fullRoyaltyfree",
              "resolutionType": "hd"
            });
            expect(response.body.data[43]).to.deep.equal({
              "licenseId": "9ee9d50c-bb1a-4df1-8a15-1446d2104959",
              "title": "4K - Full Royalty Free (RF)",
              "shortDescription": "Freedom for all uses forever – multiple projects",
              "longDescription": "Freedom for all uses forever – multiple projects",
              "price": 285.00,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rf",
              "productType": "video",
              "pictureType": "",
              "isEditorial": false,
              "orderBy": 5,
              "hasEditorialLicense": true,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "fullRoyaltyfree",
              "resolutionType": "4k"
            });
            expect(response.body.data[44]).to.deep.equal({
              "licenseId": "b084e96c-8a29-4e33-b8c1-d0bc130e6d15",
              "title": "4K - Full Royalty Free (RF)",
              "shortDescription": "Freedom for all uses forever – multiple projects",
              "longDescription": "Freedom for all uses forever – multiple projects. Editorial use only.",
              "price": 285.00,
              "currency": "GBP",
              "usageRestrictions": "",
              "licenseType": "rf",
              "productType": "video",
              "pictureType": "",
              "isEditorial": true,
              "orderBy": 5,
              "hasEditorialLicense": false,
              "excludedForRfEditorial": false,
              "pond5LicenseType": "fullRoyaltyfree",
              "resolutionType": "4k"
            });
           return done();
        });
    }); 

    

    it('Standard License : error', (done) => {
      cy.request(Cypress.env('baseurl')+'/microservices/licenses/managelicenses.asmx/GetStandardLicenses?currency=&langcode=').as('comments')
      cy.get('@comments').should((response) => {
          expect(response.body.error).to.deep.contains({
              "code": 401,
              "type": "Unauthorized"
          });
          return done();
      });
    });
    
})

